name: OpenWrt Custom Build

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.latest.conclusion }}
    steps:
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG=`git ls-remote https://github.com/openwrt/openwrt | grep -E -o 'v19.07\.[0-9]+' | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+'`
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - id: latest
        name: Check Published Version
        run: curl 'https://downloads.hackinggate.com' | grep ${OPENWRT_VERSION} | grep 'tl-wr703n'
  build:
    needs: check
    if: needs.check.outputs.latest == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG=`git ls-remote https://github.com/openwrt/openwrt | grep -E -o 'v19.07\.[0-9]+' | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+'`
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - name: Custom Build
        run: |
          OPENWRT_TAG=${{ env.OPENWRT_TAG }}
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          ./custom-build-with-openwrt-tag-version.sh
      - name: Make
        run: |
          cd openwrt
          make -j4 V=s
      - name: Tree
        run: |
          sudo apt install tree
          tree openwrt/bin/
      - name: Move direcotries
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          mkdir openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m
          mv openwrt/bin/targets/ar71xx/generic/openwrt-${OPENWRT_VERSION}-*-tl-703n-v1-* openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m
          mv openwrt/bin/targets/ar71xx/generic/profiles.json openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m
          rm -rf openwrt
      - name: Generate gh-pages
        run: ./generate-page.sh
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: .
          clean: true
