name: OpenWrt Custom Build

on: push

jobs:
  build-19.07:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG=`git ls-remote https://github.com/openwrt/openwrt | grep -E -o 'v19.07\.[0-9]+' | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+'`
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - name: Clone Latest OpenWrt
        run: |
          OPENWRT_TAG=${{ env.OPENWRT_TAG }}
          ./clone-with-openwrt-tag.sh
      - name: Configure Build
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          ./configure-build.sh
