name: OpenWrt TP-Link WR703N

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "9 0/12 * * 2-6"

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  check:
    outputs:
      latest: ${{ steps.latest.outputs.is_latest }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG_LIST=`git ls-remote --tags https://github.com/openwrt/openwrt | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+($|-rc[0-9]+$)'`
          OPENWRT_TAG=`echo ${OPENWRT_TAG_LIST} | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '^[0-9]+\.[0-9]+\.[0-9]+.*$'`
          IPQ806X_GENERIC_IMAGEBUILDER=`curl -s -o /dev/null --head -w "%{http_code}" https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/ipq806x/generic/openwrt-imagebuilder-${OPENWRT_VERSION}-ipq806x-generic.Linux-x86_64.tar.xz`
          if [[ "IPQ806X_GENERIC_IMAGEBUILDER" != 200 ]]; then
            OPENWRT_TAG=`echo ${OPENWRT_TAG_LIST} | tail -2 | head -1`
            OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '^[0-9]+\.[0-9]+\.[0-9]+.*$'`
          fi
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - id: latest
        name: Check Published Version
        run: |
          PUBLISHED_VERSION=`curl 'https://downloads.hackinggate.com' | grep 'tplink_tl-wr703n' | grep -E -o ${OPENWRT_VERSION} | tail -1`
          echo "${OPENWRT_VERSION} is latest"
          if [[ "$OPENWRT_VERSION" == "$PUBLISHED_VERSION" ]]; then
            echo "${OPENWRT_VERSION} is published for tplink_tl-wr703n"
            echo "::set-output name=is_latest::true"
          else
            echo "${OPENWRT_VERSION} is NOT published for tplink_tl-wr703n"
          fi
  build:
    needs: check
    if: ${{ needs.check.outputs.latest != 'true' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG_LIST=`git ls-remote --tags https://github.com/openwrt/openwrt | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+($|-rc[0-9]+$)'`
          OPENWRT_TAG=`echo ${OPENWRT_TAG_LIST} | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '^[0-9]+\.[0-9]+\.[0-9]+.*$'`
          IPQ806X_GENERIC_IMAGEBUILDER=`curl -s -o /dev/null --head -w "%{http_code}" https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/ipq806x/generic/openwrt-imagebuilder-${OPENWRT_VERSION}-ipq806x-generic.Linux-x86_64.tar.xz`
          if [[ "IPQ806X_GENERIC_IMAGEBUILDER" != 200 ]]; then
            OPENWRT_TAG=`echo ${OPENWRT_TAG_LIST} | tail -2 | head -1`
            OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '^[0-9]+\.[0-9]+\.[0-9]+.*$'`
          fi
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python \
          jq tree
      - name: Build WR703N with imagebuilder
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          ./wr703n-openwrt-imagebuilder-build.sh
      - name: Checkout gh-pages
        run : |
          git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch origin gh-pages
          git checkout gh-pages
      - name: Override Files
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          rm -rf openwrt-${OPENWRT_VERSION}-ath79-tiny-tplink_tl-wr703n
          mv openwrt-imagebuilder-${OPENWRT_VERSION}-ath79-tiny.Linux-x86_64/bin/targets/ath79/tiny openwrt-${OPENWRT_VERSION}-ath79-tiny-tplink_tl-wr703n
          rm -rf openwrt-imagebuilder-*
          rm openwrt-${OPENWRT_VERSION}-ath79-tiny-tplink_tl-wr703n/sha256sums
      - name: Generate gh-pages
        run: |
          git checkout - -- generate-page.sh
          ./generate-page.sh
          rm generate-page.sh
      - name: Tree
        run: | 
          sudo apt install tree
          tree
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .
          clean: true
          dry-run: ${{ github.event_name == 'pull_request' }}
